export type GuideSection = { id: string; title: string; paragraphs: string[]; bullets?: string[]; table?: { headers: string[]; rows: string[][] }; sources?: string[] };
export type MakerGuide = { slug: string; title: string; description: string; answer: string; category: string; image: string; sections: GuideSection[]; sources: { id: string; title: string; url: string }[]; faq: { question: string; answer: string }[]; tool: { href: string; label: string } };
export const guideDate = "2026-09-23";
export const makerGuides: MakerGuide[] = [
  {
    slug: "laser-engraving-business-startup-costs", title: "Laser Engraving Business Startup Costs in the U.S.", category: "STARTUP BUDGET",
    description: "Build a U.S. laser engraving startup budget with a $5,500 worked example, operating break-even, and equipment payback scenarios in USD.",
    image: "/images/opportunities/personalized-tumbler.webp",
    answer: "Budget for the whole workflow, not just the laser. In our illustrative U.S. workshop plan, $4,250 of setup costs, $450 of opening inventory, and $800 of working cash require $5,500 to launch. These are planning assumptions, not equipment quotes or an industry average. Your required cash depends on the product, workspace, and actual supplier quotes.",
    sections: [
      { id: "budget", title: "What belongs in your startup budget?", paragraphs: ["Separate one-time setup, saleable inventory, and cash held for ongoing bills. This makes it easier to see which purchases can wait until buyers have paid for a small batch. The SBA recommends identifying startup expenses before estimating capital needs.", "The example below assumes you already have a suitable workspace and computer. It excludes rent deposits, delivery, sales tax on purchases, insurance, permits, and any building or electrical changes. Obtain local quotes for those items before treating this as a cash requirement."], table: { headers: ["Planning item", "Assumed USD"], rows: [["Laser", "$3,000"], ["Fixtures and accessories", "$500"], ["Extraction and ventilation", "$600"], ["Initial design software allowance", "$150"], ["Setup subtotal", "$4,250"], ["Opening blanks", "$300"], ["Opening packaging", "$150"], ["Working cash reserve", "$800"], ["Total launch cash", "$5,500"]] }, sources: ["sba"] },
      { id: "quotes", title: "Turn the example into a purchase plan", paragraphs: ["Start with one item you can sell repeatedly: for example, a personalized tumbler for a local organization. Ask for quotes for the blank, fixture, packing material, and delivery together. A low machine price does not resolve a workflow that needs expensive accessories or slow manual alignment.", "Confirm the material and process with the equipment supplier, including extraction requirements and workspace suitability. Replace every allowance above with a quote before ordering. Keep a separate line for items billed each month; a recurring software subscription cannot disappear from operating costs just because its first payment appears in the startup budget."], bullets: ["Time five sample orders from artwork intake through packing.", "Record damaged blanks and remakes as well as successful samples.", "Use paid demand to decide the next purchase; ten paid trial orders are a useful small experiment, not proof of sustainable demand."] },
      { id: "break-even", title: "How many orders cover monthly bills?", paragraphs: ["Operating break-even is monthly fixed costs divided by contribution per order. Contribution means selling revenue after the costs caused by that order: materials, hands-on labor, marketplace fees, packaging, and any shipping you pay. It is not simply price minus the blank.", "Assume $250 in monthly fixed costs and $12 of contribution per order after those variable costs. You need 21 whole orders to cover the monthly bills because $250 ÷ $12 = 20.83. That covers current operations; it has not yet repaid the setup investment."], sources: ["sba"] },
      { id: "payback", title: "Equipment payback changes with actual orders", paragraphs: ["Use the remaining monthly contribution after fixed costs to estimate simple setup payback. We use the $4,250 setup subtotal here, not the $5,500 launch cash total: opening inventory and the cash reserve are tracked separately. This avoids counting the same materials again as both an investment and a per-order cost.", "These scenarios hold price, unit contribution, and fixed costs constant. They exclude financing, income taxes, changes in working capital, and replacement purchases. They are arithmetic scenarios, not sales forecasts."], table: { headers: ["Orders / month", "After $250 fixed costs", "Simple setup payback"], rows: [["20", "−$10 / month", "No payback"], ["40", "$230 / month", "18.5 months"], ["100", "$950 / month", "4.5 months"]] } },
      { id: "next-step", title: "Validate the order before buying capacity", paragraphs: ["Write down a buyer, an offer, a delivery date, and a price. Quote a small batch with the actual personalization and packing work included. If the contribution is too low, test the offer, batch size, or process before assuming a larger machine will fix it.", "Use our ROI calculator for an initial production and payback model, then reconcile its inputs with this full budget. The calculator is a planning tool; use your own order ledger to track fees, returns, overhead, and cash movement. Review the budget after the first paid batch and again before adding a second product."] },
    ],
    sources: [{ id: "sba", title: "U.S. Small Business Administration — Plan your business: startup costs and break-even", url: "https://www.sba.gov/counseling/plan-your-business/" }],
    faq: [{ question: "Is $5,500 enough to start a laser engraving business?", answer: "It covers only the assumptions in this example. It is not a minimum or market average. Add your workspace, delivery, taxes, insurance, and local requirements to actual equipment quotes." }, { question: "Does break-even mean the laser has paid for itself?", answer: "No. Operating break-even covers ongoing costs. Setup payback uses what remains after those costs to recover the original setup investment." }],
    tool: { href: "/calculator/laser-roi", label: "Build your ROI model" },
  },
  {
    slug: "etsy-tumbler-pricing-us", title: "How to Price Laser-Engraved Tumblers on Etsy (U.S.)", category: "ETSY PRICING",
    description: "Price a laser-engraved tumbler for U.S. Etsy sales: a $32 example with listing fees, payment processing, labor, shipping, and contribution.",
    image: "/images/opportunities/personalized-tumbler.webp",
    answer: "For a U.S. Etsy seller, price an engraved tumbler after the blank, labor, packaging, shipping, and marketplace fees. Our $32 free-shipping example leaves about $9.48 per order before fixed overhead and income taxes. Price minus the $8.20 blank is $23.80, but that is not take-home profit.",
    sections: [
      { id: "fees", title: "Which Etsy fees enter the calculation?", paragraphs: ["For this single-item example, allocate a $0.20 listing fee and a 6.5% transaction fee on the item price. Etsy also applies the transaction fee to charged shipping and gift wrapping; U.S. sales tax is excluded. Listing renewals and unsold listings can add costs beyond this allocation.", "For a U.S. bank account, Etsy Payments processing is 3% plus $0.25. Its base includes shipping and sales tax. These fee bases differ, so combining them into one flat percentage can miss costs. Check Etsy’s current policies before updating a live price."], sources: ["fees", "payments"] },
      { id: "example", title: "A $32 tumbler: the complete worked example", paragraphs: ["Assume one tumbler sold for $32, with no separate shipping charge or gift wrap. For arithmetic only, assume the buyer pays 8% sales tax ($2.56). That is not a nationwide tax rate: the applicable amount depends on the transaction. Sales tax collected for remittance is not included in the $32 of seller revenue.", "The blank costs $8.20. Ten minutes of hands-on work at an assumed $24 hourly rate costs $4. Machine runtime is not necessarily hands-on time; include actual setup, personalization checks, cleanup, customer communication, and packing in your labor record."], table: { headers: ["Item", "Calculation", "USD"], rows: [["Seller revenue", "Item, shipping included", "$32.00"], ["Blank", "Assumed landed cost", "−$8.20"], ["Hands-on labor", "10 minutes × $24/hour", "−$4.00"], ["Packaging", "Assumed", "−$1.25"], ["Carrier postage", "Assumed", "−$5.50"], ["Listing allocation", "One listing fee", "−$0.20"], ["Transaction fee", "$32 × 6.5%", "−$2.08"], ["Payment processing", "$34.56 × 3% + $0.25", "−$1.29"], ["Contribution", "Before fixed overhead and income taxes", "$9.48"]] } },
      { id: "advertising", title: "Stress-test an order attributed to Offsite Ads", paragraphs: ["Etsy’s Offsite Ads charge can be 15% or 12% on attributed orders, depending on the policy’s sales threshold and participation rules. In this U.S. example, a 15% fee on $32 removes another $4.80, leaving about $4.68. A 12% fee removes $3.84, leaving about $5.64.", "Do not apply that cost to every order unless every order is attributed. Equally, do not ignore it when deciding whether an individual promoted order is worth fulfilling. Keep ordinary Etsy Ads spend separate so it is not confused with the Offsite Ads fee."], sources: ["fees"] },
      { id: "missing-costs", title: "What the $9.48 still needs to cover", paragraphs: ["Contribution is the amount available for fixed workshop expenses and business profit after the modeled order costs. This example excludes rent, insurance, machine depreciation, subscriptions, shop setup fees, extra listing renewals, currency conversion, discounts, returns, and other advertising. Add the items that apply to your shop.", "A remake can consume another blank, another shipping label, and more labor while generating no new revenue. Track actual remake costs over several batches and allocate a reserve per order. Use packed weight and destination quotes for shipping; a single sample postage assumption should not become a promise to ship anywhere at that price."], bullets: ["Quote each personalization tier separately if artwork effort differs.", "Recalculate the contribution after a coupon or bundle discount.", "Set a revision limit and approval deadline in the offer.", "Reconcile the estimate against the order’s actual payment statement."] },
      { id: "test-price", title: "Test willingness to pay, not just your spreadsheet", paragraphs: ["A cost-based price tells you what a sale leaves behind. It does not prove customers will pay that price. Offer one clear design to a specific buyer group and record paid orders, production time, remakes, and delivery costs. Avoid reading views or favorites as purchases.", "Use the tumbler calculator for the initial material and production model, then subtract the channel, labor, and fulfillment costs above where they are not already included. Compare offers on contribution per hands-on hour as well as per item. A higher-priced custom order can earn less per hour when revisions consume the afternoon."] },
    ],
    sources: [{ id: "fees", title: "Etsy — Fees & Payments Policy", url: "https://www.etsy.com/legal/fees/" }, { id: "payments", title: "Etsy Help — Payment processing fees by country", url: "https://help.etsy.com/hc/en-us/articles/115015628847-What-are-Payment-Processing-Fees-for-Selling-on-Etsy" }],
    faq: [{ question: "Is free shipping actually free for the seller?", answer: "No. The carrier still charges you. Include postage in the cost model even if the buyer sees no separate shipping charge." }, { question: "Is a $32 selling price a recommended market price?", answer: "No. It is an illustrative input. Validate the price with your own buyers and replace every assumed cost with actual records." }],
    tool: { href: "/calculator/tumbler-profit", label: "Start a tumbler cost model" },
  },
  {
    slug: "how-to-price-3d-prints", title: "How to Price 3D Prints: A U.S. Seller’s Cost Model", category: "3D PRINTING",
    description: "Price 3D prints beyond filament: a USD worked example including machine wear, electricity, failed prints, labor, fees, and target contribution.",
    image: "/images/opportunities/3d-desk-organizer.webp",
    answer: "Price a 3D print from its cost per successful unit, then allow for sales fees and your target contribution. Our example costs about $11.99 before channel fees and needs a $20.50 rounded-up price for a 30% contribution margin with an assumed 10% plus $0.30 fee. Filament alone costs $2.64 and misses most of the order economics.",
    sections: [
      { id: "production", title: "Calculate the cost of one print attempt", paragraphs: ["Start with sliced material weight and runtime, then replace those estimates with measurements from completed jobs. Prusa’s calculator separates filament, electricity, labor, machine upkeep, and other costs; the same categories are useful for a small commercial quote.", "Here we assume 120 grams of filament at $22 per kilogram and a six-hour print. We assign $0.25 per machine hour for wear and upkeep. Electricity uses an assumed average draw of 120 watts and an assumed $0.18 per kWh. Neither the electricity price nor the wear rate is a U.S. average: use your bill, measurements, and replacement budget."], table: { headers: ["Production input", "Calculation", "USD / attempt"], rows: [["Filament", "0.12 kg × $22", "$2.64"], ["Machine wear", "6 hours × $0.25", "$1.50"], ["Electricity", "0.12 kW × 6 hours × $0.18", "$0.13"], ["Attempt subtotal", "Before failures and hands-on labor", "$4.27"]] }, sources: ["prusa"] },
      { id: "failure", title: "Convert attempts into successful units", paragraphs: ["If 10% of attempts fail and each failure consumes a full attempt’s production cost, the success rate is 90%. Divide the unrounded $4.2696 attempt cost by 0.90: expected production cost is $4.744 per successful unit. Multiplying by 1.10 would understate the repeated attempts needed.", "This is deliberately a simple loss model. Early failures may use less material and energy; cleanup may add more labor. Track actual failed material, occupied machine time, and recovery work. Add 15 minutes of hands-on labor at $24 per hour ($6) and $1.25 packaging per successful item. The modeled unit cost becomes $11.994, or about $11.99 before channel fees. It excludes shipping, design work, fixed overhead, and taxes."] },
      { id: "price", title: "Solve for a price that leaves a contribution", paragraphs: ["For an assumed sales channel charging 10% of revenue plus $0.30 per order, and a target contribution margin of 30%, use: price = (unit cost + fixed order fee) ÷ (1 − percentage fee − target margin). These are hypothetical channel fees, not Etsy’s fee schedule.", "With unrounded inputs, ($11.994 + $0.30) ÷ (1 − 0.10 − 0.30) = $20.49. Rounding up to the next $0.10 gives $20.50. At that price, the model leaves about $6.16 per order before fixed expenses and income taxes. The denominator must be positive; a fee percentage and target margin adding to 100% cannot produce a finite price.", "A 30% markup is different: multiplying cost by 1.30 does not produce a 30% margin, especially after fees. If you pay for shipping, add it to unit cost first. If design work is bespoke, price it separately or allocate its paid time to the actual number of units ordered."] },
      { id: "capacity", title: "Check machine hours and hands-on hours separately", paragraphs: ["A six-hour print does not necessarily require six hours of paid labor. It does occupy a machine for six hours, and that capacity limits how many orders you can promise. Measure setup, support removal, finishing, quality checks, packing, and buyer communication as hands-on work.", "Batch printing can reduce setup time, but a failed plate can affect multiple units. Validate the batch process before assuming every print-bed position is saleable capacity. Leave room for maintenance and reprints when setting delivery dates; theoretical round-the-clock output is not a production commitment."] },
      { id: "offer", title: "Validate the design, sales channel, and offer", paragraphs: ["Before quoting, check that you can commercially use the model and that the item meets the chosen marketplace’s rules. Those are separate questions. Etsy’s creativity standards say items produced with computerized tools such as 3D printers must be based on the seller’s original design; a downloaded model’s commercial license alone does not establish that requirement.", "Choose one use case, make a sample, and quote a small paid batch. Record willingness to pay alongside actual cost per good unit. Use the ROI calculator for initial production economics, then add this guide’s failure, labor, channel, and fulfillment adjustments where the tool does not already include them. Compare the resulting contribution with the hours and cash the order ties up."], sources: ["etsy"] },
    ],
    sources: [{ id: "prusa", title: "Prusa Research — 3D printing price calculator", url: "https://blog.prusa3d.com/3d-printing-price-calculator_38905/" }, { id: "etsy", title: "Etsy — Creativity Standards", url: "https://www.etsy.com/legal/creativity/" }],
    faq: [{ question: "Can I price a print using filament cost times three?", answer: "That shortcut does not account for runtime, labor, failures, fulfillment, or selling fees. Build a cost per successful unit and test the resulting offer with buyers." }, { question: "Does this $20.50 example include shipping?", answer: "No. Add the shipping cost you pay before solving for price, and check which fee bases include any shipping charged to the buyer." }],
    tool: { href: "/calculator/laser-roi?product=3d-desk-organizers", label: "Model a 3D printing product" },
  },
];

export function guidePath(slug: string) { return `/learn/${slug}/`; }
export function guideStructuredData(guide: MakerGuide, base: string) {
  const url = `${base}${guidePath(guide.slug)}`;
  return { "@context": "https://schema.org", "@graph": [
    { "@type": "Article", "@id": `${url}#article`, headline: guide.title, description: guide.description, abstract: guide.answer, mainEntityOfPage: url, url, inLanguage: "en-US", datePublished: guideDate, dateModified: guideDate, image: `${base}${guide.image}`, author: { "@type": "Organization", "@id": `${base}/#organization`, name: "Maker Business Lab", url: `${base}/about/` }, publisher: { "@id": `${base}/#organization` }, citation: guide.sources.map(source => source.url) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${base}/` }, { "@type": "ListItem", position: 2, name: "Learn", item: `${base}/learn/` }, { "@type": "ListItem", position: 3, name: guide.title, item: url }] },
  ] };
}
