export type OpportunityCategory = "laser" | "3d-printing" | "heat-press";

export type Opportunity = {
  id: string;
  rank: number;
  title: string;
  titleZh: string;
  category: OpportunityCategory;
  process: string;
  processZh: string;
  score: number;
  sellingPrice: number;
  materialCost: number;
  grossProfit: number;
  productionMinutes: number;
  image: string;
  demand: number;
  margin: number;
  competition: number;
  skill: number;
  speed: number;
  tags: string[];
  channels: string[];
  equipmentTags: string[];
  startingBudget: number;
  evidence: string;
  evidenceZh: string;
};

export const opportunities: Opportunity[] = [
  {
    id: "personalized-tumblers",
    rank: 1,
    title: "Personalized Tumblers",
    titleZh: "个性化保温杯",
    category: "laser",
    process: "Laser engraving",
    processZh: "激光雕刻",
    score: 82,
    sellingPrice: 32,
    materialCost: 8.2,
    grossProfit: 23.8,
    productionMinutes: 4,
    image: "/images/personalized-tumbler.png",
    demand: 84,
    margin: 86,
    competition: 58,
    skill: 72,
    speed: 90,
    tags: ["personalized", "gifts", "events", "side-income", "repeat-orders"],
    channels: ["Etsy", "Craft fairs", "Corporate gifts"],
    equipmentTags: ["tumblers", "drinkware", "speed"],
    startingBudget: 3_000,
    evidence: "Strong personalization fit with repeatable blanks and simple price testing.",
    evidenceZh: "标准化杯坯便于测试定价，也适合个性化与重复订单。",
  },
  {
    id: "3d-desk-organizers",
    rank: 2,
    title: "3D-Printed Desk Organizers",
    titleZh: "3D 打印桌面收纳",
    category: "3d-printing",
    process: "3D printing",
    processZh: "3D 打印",
    score: 76,
    sellingPrice: 29.99,
    materialCost: 11.59,
    grossProfit: 18.4,
    productionMinutes: 210,
    image: "/images/3d-desk-organizer.png",
    demand: 76,
    margin: 72,
    competition: 62,
    skill: 66,
    speed: 44,
    tags: ["home", "desk", "functional", "first-sale", "design"],
    channels: ["Etsy", "Shopify", "Local offices"],
    equipmentTags: ["3d-printing", "functional-parts"],
    startingBudget: 500,
    evidence: "Functional products can be differentiated through size, modularity, and niche fit.",
    evidenceZh: "功能型产品可通过尺寸、模块化和细分场景形成差异。",
  },
  {
    id: "acrylic-wedding-signs",
    rank: 3,
    title: "Acrylic Wedding Signs",
    titleZh: "亚克力婚礼标牌",
    category: "laser",
    process: "Laser cutting",
    processZh: "激光切割",
    score: 73,
    sellingPrice: 59.99,
    materialCost: 32.39,
    grossProfit: 27.6,
    productionMinutes: 24,
    image: "/images/acrylic-wedding-sign.png",
    demand: 74,
    margin: 69,
    competition: 55,
    skill: 70,
    speed: 68,
    tags: ["weddings", "events", "personalized", "premium", "local"],
    channels: ["Etsy", "Wedding planners", "Local venues"],
    equipmentTags: ["acrylic", "signs", "large work area"],
    startingBudget: 5_000,
    evidence: "Higher-ticket event products reward personalization and local partnerships.",
    evidenceZh: "高客单活动产品适合个性化，并能通过本地婚庆合作获客。",
  },
  {
    id: "laser-leather-patches",
    rank: 4,
    title: "Custom Leather Patches",
    titleZh: "定制皮革章",
    category: "laser",
    process: "Laser engraving",
    processZh: "激光雕刻",
    score: 79,
    sellingPrice: 11,
    materialCost: 1.9,
    grossProfit: 9.1,
    productionMinutes: 3,
    image: "/images/laser-leather-patches.jpg",
    demand: 80,
    margin: 83,
    competition: 61,
    skill: 70,
    speed: 92,
    tags: ["personalized", "gifts", "fashion", "repeat-orders", "small-batch"],
    channels: ["Etsy", "Hat makers", "Local brands"],
    equipmentTags: ["leather", "engraving", "batch-production"],
    startingBudget: 1_500,
    evidence: "Low material cost and fast batching make patches useful for testing logos, niches, and wholesale orders.",
    evidenceZh: "低材料成本与快速批量加工，适合测试 Logo、细分风格和小额批发订单。",
  },
  {
    id: "3d-geometric-planters",
    rank: 5,
    title: "3D-Printed Planters",
    titleZh: "3D 打印几何花盆",
    category: "3d-printing",
    process: "3D printing",
    processZh: "3D 打印",
    score: 74,
    sellingPrice: 34,
    materialCost: 8.5,
    grossProfit: 25.5,
    productionMinutes: 480,
    image: "/images/3d-geometric-planter.jpg",
    demand: 75,
    margin: 79,
    competition: 59,
    skill: 68,
    speed: 38,
    tags: ["home", "decor", "design", "gifts", "first-sale"],
    channels: ["Etsy", "Plant shops", "Design markets"],
    equipmentTags: ["3d-printing", "planters", "large-format"],
    startingBudget: 500,
    evidence: "Distinctive geometry, colors, and functional drainage create room for design-led pricing.",
    evidenceZh: "造型、配色和排水结构都能形成差异，为设计溢价创造空间。",
  },
  {
    id: "layered-wood-wall-art",
    rank: 6,
    title: "Layered Wood Wall Art",
    titleZh: "分层木艺壁饰",
    category: "laser",
    process: "Laser cutting",
    processZh: "激光切割",
    score: 77,
    sellingPrice: 89,
    materialCost: 24,
    grossProfit: 65,
    productionMinutes: 55,
    image: "/images/layered-wood-wall-art.jpg",
    demand: 78,
    margin: 82,
    competition: 57,
    skill: 76,
    speed: 60,
    tags: ["home", "decor", "premium", "gifts", "design"],
    channels: ["Etsy", "Interior designers", "Craft fairs"],
    equipmentTags: ["wood", "large work area", "batch-production"],
    startingBudget: 3_500,
    evidence: "Layer count, size, and finish support premium bundles while one design can be produced repeatedly.",
    evidenceZh: "层数、尺寸和表面处理可组合成高客单版本，同时同一设计能重复生产。",
  },
  {
    id: "heat-press-tote-bags",
    rank: 7,
    title: "Personalized Heat-Press Totes",
    titleZh: "定制热转印托特包",
    category: "heat-press",
    process: "Heat press",
    processZh: "热压转印",
    score: 78,
    sellingPrice: 24,
    materialCost: 7.8,
    grossProfit: 16.2,
    productionMinutes: 6,
    image: "/images/heat-press-tote.png",
    demand: 81,
    margin: 76,
    competition: 63,
    skill: 64,
    speed: 86,
    tags: ["personalized", "gifts", "events", "fashion", "first-sale", "side-income"],
    channels: ["Etsy", "School teams", "Local events"],
    equipmentTags: ["tote bags", "apparel", "heat transfer", "dtf"],
    startingBudget: 500,
    evidence: "A standard blank plus a ready-to-press transfer creates short cycles and makes it easy to test designs for events, teams, and local brands.",
    evidenceZh: "标准化坯料配合即烫转印图，可快速完成单件制作，适合测试活动、团队和本地品牌设计。",
  },
];

export const opportunityById = Object.fromEntries(opportunities.map((item) => [item.id, item])) as Record<string, Opportunity>;
